<a href="https://colab.research.google.com/github/shivangi-975/Data-Preparation-for-ML/blob/main/How_to_know_which_features_is_missingipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing libraries

In [ ]:
import pandas as pd
import numpy as np

from sklearn.impute import MissingIndicator

In [ ]:
features = [[4, 2, 1], 
            [24, 12, 6], 
            [8, 4, 2], 
            [28, 14, 7], 
            [32, 16, -1], 
            [600, 300, 150], 
            [-1, 60, 30], 
            [-1, 4, 1]]

In [ ]:
indicator = MissingIndicator(missing_values=-1)

Only shows those features which have missing values

In [ ]:
mask_missing_values_only = indicator.fit_transform(features)

mask_missing_values_only

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True],
       [False, False],
       [ True, False],
       [ True, False]])

In [ ]:
indicator.features_

array([0, 2])

If you want to show the features which doesn't have any missing value ....then use features="all

In [ ]:
indicator = MissingIndicator(missing_values=-1, features="all")

In [ ]:
mask_all = indicator.fit_transform(features)

mask_all

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [ ]:
indicator.features_

array([0, 1, 2])